language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

install:
- cd $TRAVIS_BUILD_DIR/StoryGraph
- dotnet restore

script:
- cd $TRAVIS_BUILD_DIR/StoryGraph
- dotnet build
- dotnet test Test/Test.csproj