FROM microsoft/dotnet:2-sdk
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.sln ./
COPY Model/Model.csproj ./Model/
COPY Test/Test.csproj ./Test/
RUN dotnet restore

# Copy everything else and run test
COPY . ./
ENTRYPOINT ["dotnet", "test", "Test"]